spring:
  application:
    name: Library - API
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: admin
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1049577894942-8gvm6qfv4u69khui3un04aao9c4pb9fu.apps.googleusercontent.com
            client-secret: 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